### ISSUE TITLE
Phantom is undefined

### ISSUE THREAD

**Issue by world33** [bitjson/webshotgun#1]
Hi, I confess I am a noob when it comes to npm and related scripts.

I installed webshotgun but when I run the example command you provide:
**webshotgun --dest 'shots' google.com reddit.com nodejs.org**

I get the error message  **"phantom" is undefined line 3**

Do I have to install phantomjs even if it uses slimerjs?

Thanks for any help.

**Comment by bitjson** [comment]
Hey @world33 could copy paste the whole error message? Is there any other information?

I'm afraid I'm not really maintaining this repo, so I'm not sure if you'll want to spend too much time getting it working. The space has really advanced in the past few years – if you haven't seen it, I'd recommend taking a look at [Puppeteer](https://github.com/GoogleChrome/puppeteer/).

**Comment by bitjson** [comment]
I suppose if I get around to needing this project again, I might try refactoring to use Puppeteer and providing the same CLI. I'm sorry I don't really have a timeline for that, though.

**Comment by world33** [comment]
Thanks for the tip bitjson . I will look into the Puppeteer. I need to make screenshots in bulk and there are so many old resources around github that it is hard to find the right platform and script. Thank you again.

**Comment by bitjson** [comment]
Happy to help! Thanks for opening the issue.
